<a href="https://colab.research.google.com/github/Sibahle01/Itroduction_to_numPy/blob/main/Introduction_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**What is NumPy?**
NumPy (Numerical Python) is a powerful library in Python used for numerical computing. It provides support for working with arrays (similar to lists but more efficient) and mathematical operations on them. NumPy is the foundation of many data science and machine learning libraries like Pandas and TensorFlow.

In [ ]:
pip install numpy

In [ ]:
import numpy as np

Creating Arrays

1D Array:

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


2D Array:


In [ ]:
import numpy as np
matrix = np.array([[1, 2], [3, 4]])
print(matrix)

[[1 2]
 [3 4]]


**Shape**: Gives the dimensions of the array.


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.shape)

(3, 2)


**Size**: Total number of elements.

In [ ]:
print(arr.size)

6


**Data** Type:int or str or float

In [ ]:
print(arr.dtype)

int64


**Mathematical Operations Example**

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


**Statical Operations**

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr.mean())
print(arr.sum())
print(arr.max())

3.0
15
5


**Practical Use Case**

In [ ]:
temps = np.array([30.5, 32.1, 33.8, 31.5, 29.9, 28.7, 27.5])
mean_temp = temps.mean()
print(f"The average temperature is {mean_temp:.2f}°C")

The average temperature is 30.57°C
